version: "3"
services: 
  lavalink:
    image: fredboat/lavalink:dev
    ports:
      - '6969:6969'
    container_name: music-lavalink
    hostname: lavalink
    restart: unless-stopped
    volumes:
      - ./application.yml:/opt/Lavalink/application.yml:ro
      - ./media:/media

